import type {
  ActivityCategory,
  ActivityRecord,
  AssignmentProduct,
  EmissionFactor,
  GhgScope,
  LifecycleStage,
  PcfDataset,
} from "./types";

export const assignmentProduct: AssignmentProduct = {
  code: "CT-045",
  nameKo: "컴퓨터 화면",
  nameEn: "Computer Screen",
  productionQuantity: 1,
  productionUnit: "과제 데이터 묶음",
};

export const activityCategoryLabels: Record<ActivityCategory, string> = {
  electricity: "전기",
  material: "원소재",
  transport: "운송",
};

export const scopeLabels: Record<GhgScope, string> = {
  scope2: "Scope 2 - 구매 전력",
  scope3: "Scope 3 - 공급망 및 물류",
};

export const lifecycleStageLabels: Record<LifecycleStage, string> = {
  "manufacturing-energy": "제조 에너지",
  "raw-materials": "원소재 조달",
  "upstream-transport": "상류 운송",
};

export const assignmentActivities: ActivityRecord[] = [
  {
    id: "electricity-2025-01-01-001",
    date: "2025-01-01",
    category: "electricity",
    label: "한국전력",
    quantity: 110,
    unit: "kWh",
    scope: "scope2",
    lifecycleStage: "manufacturing-energy",
  },
  {
    id: "electricity-2025-02-01-001",
    date: "2025-02-01",
    category: "electricity",
    label: "한국전력",
    quantity: 112,
    unit: "kWh",
    scope: "scope2",
    lifecycleStage: "manufacturing-energy",
  },
  {
    id: "electricity-2025-03-01-001",
    date: "2025-03-01",
    category: "electricity",
    label: "한국전력",
    quantity: 115,
    unit: "kWh",
    scope: "scope2",
    lifecycleStage: "manufacturing-energy",
  },
  {
    id: "electricity-2025-04-01-001",
    date: "2025-04-01",
    category: "electricity",
    label: "한국전력",
    quantity: 130,
    unit: "kWh",
    scope: "scope2",
    lifecycleStage: "manufacturing-energy",
  },
  {
    id: "electricity-2025-05-01-001",
    date: "2025-05-01",
    category: "electricity",
    label: "한국전력",
    quantity: 120,
    unit: "kWh",
    scope: "scope2",
    lifecycleStage: "manufacturing-energy",
  },
  {
    id: "electricity-2025-06-01-001",
    date: "2025-06-01",
    category: "electricity",
    label: "한국전력",
    quantity: 110,
    unit: "kWh",
    scope: "scope2",
    lifecycleStage: "manufacturing-energy",
  },
  {
    id: "electricity-2025-07-01-001",
    date: "2025-07-01",
    category: "electricity",
    label: "한국전력",
    quantity: 120,
    unit: "kWh",
    scope: "scope2",
    lifecycleStage: "manufacturing-energy",
  },
  {
    id: "electricity-2025-08-01-001",
    date: "2025-08-01",
    category: "electricity",
    label: "한국전력",
    quantity: 111,
    unit: "kWh",
    scope: "scope2",
    lifecycleStage: "manufacturing-energy",
  },
  {
    id: "electricity-2025-05-01-002",
    date: "2025-05-01",
    category: "electricity",
    label: "한국전력",
    quantity: 101,
    unit: "kWh",
    scope: "scope2",
    lifecycleStage: "manufacturing-energy",
  },
  {
    id: "material-plastic-1-2025-01-01-001",
    date: "2025-01-01",
    category: "material",
    label: "플라스틱 1",
    quantity: 230,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "material-plastic-1-2025-02-01-001",
    date: "2025-02-01",
    category: "material",
    label: "플라스틱 1",
    quantity: 340,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "material-plastic-2-2025-03-01-001",
    date: "2025-03-01",
    category: "material",
    label: "플라스틱 2",
    quantity: 23,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "material-plastic-1-2025-03-01-001",
    date: "2025-03-01",
    category: "material",
    label: "플라스틱 1",
    quantity: 430,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "material-plastic-1-2025-04-01-001",
    date: "2025-04-01",
    category: "material",
    label: "플라스틱 1",
    quantity: 510,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "material-plastic-1-2025-05-01-001",
    date: "2025-05-01",
    category: "material",
    label: "플라스틱 1",
    quantity: 424,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "material-plastic-2-2025-05-01-001",
    date: "2025-05-01",
    category: "material",
    label: "플라스틱 2",
    quantity: 40,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "material-plastic-1-2025-06-01-001",
    date: "2025-06-01",
    category: "material",
    label: "플라스틱 1",
    quantity: 450,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "material-plastic-1-2025-07-01-001",
    date: "2025-07-01",
    category: "material",
    label: "플라스틱 1",
    quantity: 340,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "material-plastic-2-2025-07-01-001",
    date: "2025-07-01",
    category: "material",
    label: "플라스틱 2",
    quantity: 43,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "material-plastic-1-2025-08-01-001",
    date: "2025-08-01",
    category: "material",
    label: "플라스틱 1",
    quantity: 230,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "material-plastic-1-2025-05-01-002",
    date: "2025-05-01",
    category: "material",
    label: "플라스틱 1",
    quantity: 232,
    unit: "kg",
    scope: "scope3",
    lifecycleStage: "raw-materials",
  },
  {
    id: "transport-truck-2025-01-01-001",
    date: "2025-01-01",
    category: "transport",
    label: "트럭",
    quantity: 41,
    unit: "ton-km",
    scope: "scope3",
    lifecycleStage: "upstream-transport",
  },
  {
    id: "transport-truck-2025-02-01-001",
    date: "2025-02-01",
    category: "transport",
    label: "트럭",
    quantity: 211,
    unit: "ton-km",
    scope: "scope3",
    lifecycleStage: "upstream-transport",
  },
  {
    id: "transport-truck-2025-03-01-001",
    date: "2025-03-01",
    category: "transport",
    label: "트럭",
    quantity: 123,
    unit: "ton-km",
    scope: "scope3",
    lifecycleStage: "upstream-transport",
  },
  {
    id: "transport-truck-2025-04-01-001",
    date: "2025-04-01",
    category: "transport",
    label: "트럭",
    quantity: 42,
    unit: "ton-km",
    scope: "scope3",
    lifecycleStage: "upstream-transport",
  },
  {
    id: "transport-truck-2025-05-01-001",
    date: "2025-05-01",
    category: "transport",
    label: "트럭",
    quantity: 123,
    unit: "ton-km",
    scope: "scope3",
    lifecycleStage: "upstream-transport",
  },
  {
    id: "transport-truck-2025-06-01-001",
    date: "2025-06-01",
    category: "transport",
    label: "트럭",
    quantity: 123,
    unit: "ton-km",
    scope: "scope3",
    lifecycleStage: "upstream-transport",
  },
  {
    id: "transport-truck-2025-07-01-001",
    date: "2025-07-01",
    category: "transport",
    label: "트럭",
    quantity: 41,
    unit: "ton-km",
    scope: "scope3",
    lifecycleStage: "upstream-transport",
  },
  {
    id: "transport-truck-2025-08-01-001",
    date: "2025-08-01",
    category: "transport",
    label: "트럭",
    quantity: 123,
    unit: "ton-km",
    scope: "scope3",
    lifecycleStage: "upstream-transport",
  },
  {
    id: "transport-truck-2025-05-01-002",
    date: "2025-05-01",
    category: "transport",
    label: "트럭",
    quantity: 12,
    unit: "ton-km",
    scope: "scope3",
    lifecycleStage: "upstream-transport",
  },
];

export const assignmentEmissionFactors: EmissionFactor[] = [
  {
    id: "ef-electricity-kepco-2025-v1",
    version: "assignment-2025-v1",
    validFrom: "2025-01-01",
    category: "electricity",
    label: "한국전력",
    factor: 0.456,
    factorUnit: "kgCO2e/kWh",
    source: "하나루프 과제 제공 배출계수",
  },
  {
    id: "ef-material-plastic-1-2025-v1",
    version: "assignment-2025-v1",
    validFrom: "2025-01-01",
    category: "material",
    label: "플라스틱 1",
    factor: 2.3,
    factorUnit: "kgCO2e/kg",
    source: "하나루프 과제 제공 배출계수",
  },
  {
    id: "ef-material-plastic-2-2025-v1",
    version: "assignment-2025-v1",
    validFrom: "2025-01-01",
    category: "material",
    label: "플라스틱 2",
    factor: 3.2,
    factorUnit: "kgCO2e/kg",
    source: "하나루프 과제 제공 배출계수",
  },
  {
    id: "ef-transport-truck-2025-v1",
    version: "assignment-2025-v1",
    validFrom: "2025-01-01",
    category: "transport",
    label: "트럭",
    factor: 3.5,
    factorUnit: "kgCO2e/ton-km",
    source: "하나루프 과제 제공 배출계수",
  },
];

export const assignmentPcfDataset: PcfDataset = {
  product: assignmentProduct,
  activities: assignmentActivities,
  emissionFactors: assignmentEmissionFactors,
};
